events/urls.py
# events/urls.py

from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (
    EventDetailView,
    EventCreateView,
    EventGuestListView,
    EventHostListView,
    EventUpdateView,
    InvitationResponseView,
    InvitationFoodView,
)


urlpatterns = [
    path('create/',
         EventCreateView.as_view(template_name='events/create.html'),
         name='event-create'),
    path('update/<int:pk>',
         EventUpdateView.as_view(template_name='events/update.html'),
         name='event-update'),
    path('view/<int:pk>',
         EventDetailView.as_view(template_name='events/view.html'),
         name='event-view'),
    path('view/list/guest/<str:RSVP_status>/<int:user_id>',
         EventGuestListView.as_view(template_name='events/list.html'),
         name='event-list-guest'),
    path('view/list/host/<int:user_id>',
         EventHostListView.as_view(template_name='events/list.html'),
         name='event-list-host'),
    path('RSVP/<int:pk>',
         InvitationResponseView.as_view(template_name='events/invitations/response.html'),
         name='event-response'),
    path('RSVP/<int:pk>/food',
         InvitationFoodView.as_view(template_name='events/invitations/food.html'),
         name='event-response-food'),
]

menus/urls.py
# events/urls.py

from django.urls import path
from .views import MenuCreateView, MenuUpdateView, FoodCreateView, ProporitionMenuCreateView

urlpatterns = [
    path('create/',
         MenuCreateView.as_view(template_name='menus/create.html'),
         name='menu-create'),
    path('<int:pk>/',
         MenuUpdateView.as_view(template_name='menus/update.html'),
         name='menu-update'),
    path('create/food',
         FoodCreateView.as_view(template_name='menus/add_food.html'),
         name='menu-food-create'),
    path('create/proportional',
         ProporitionMenuCreateView.as_view(template_name='menus/create_proportional.html'),
         name='menu-proportion-create')
]

project/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path('users/', include('users.urls')),
    path('events/', include('events.urls')),
    path('menus/', include('menus.urls')),
]

if not settings.DEBUG:
    urlpatterns += [re_path(r'^static/(?P<path>.*)$', serve,
                            {'document_root': settings.STATIC_ROOT})]

events/models.py
# events/models.py

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.core.exceptions import ValidationError
from menus.models import Menu, Food


class Event(models.Model):
    title = models.CharField(max_length=100)
    host = models.ForeignKey(User, on_delete=models.CASCADE, related_name='host')
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE, related_name='menu')
    guests = models.ManyToManyField(User)
    event_location = models.CharField(max_length=100, blank=True, null=True, default="TBD")
    event_date = models.DateField()
    event_time = models.TimeField(blank=True, null=True)
    RSVP_date = models.DateField()

    def __str__(self):
        return self.title

    #def clean(self):
    #    if self.RSVP_date > self.event_date:
    #        raise ValidationError({'RSVP_date': 'RSVP deadline must not be after the event.'})

    def get_absolute_url(self):
        return reverse('event-view', kwargs={'pk': self.id})


class Invitation(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    guest = models.ForeignKey(User, on_delete=models.CASCADE)
    replied = models.BooleanField(default=False, blank=True, null=True)
    attending = models.BooleanField(default=False, blank=True, null=True)
    food = models.ForeignKey(Food, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        unique_together = ('event', 'guest')

    def clean(self):
        if self.food:
            if not self.attending:
                raise ValidationError({'attending': 'A guest must attend in order to sign up for a food item.'})
            #if not self.food in self.event.menu.foods.all():
            #    raise ValidationError({'food': 'The specified food item does not exist in the menu for this event.'})

    def __str__(self):
        return ('Event: ' + self.event.title + ' -- Guest: ' + self.guest.username)

    def get_absolute_url(self):
        return reverse('event-list-guest',
                       kwargs={'RSVP_status': 'attending',
                               'guest_id': self.guest.id})

events/views.py
# events/views.py

import operator
from functools import reduce
from django.shortcuts import render, redirect, reverse
from django.db.models import Q, Count
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django import forms
from .models import Event, Invitation
from .forms import EventCreateForm, InvitationResponseForm, InvitationFoodForm, EventUpdateForm
from users.models import Profile, RestrictionTag
from menus.models import Food, Proportion
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from taggit.models import Tag
import math
import itertools


def get_top_guests(host, max_num):
    past_events = Event.objects.filter(host=host)
    top_guests = Invitation.objects.exclude(guest=host).filter(event__in=past_events) \
        .values('guest') \
        .annotate(num_invites=Count('guest')) \
        .order_by('-num_invites')
    result = top_guests[:max_num].values_list('guest', flat=True)
    return result


class EventCreateView(LoginRequiredMixin, CreateView):
    form_class = EventCreateForm

    def get_context_data(self, **kwargs):
        context = super(EventCreateView, self).get_context_data(**kwargs)
        host = self.request.user
        top_guests = get_top_guests(host, 5)
        # top_guest_names = top_guests.values_list('username')
        top_guests = User.objects.filter(id__in=top_guests)
        context['top_guests'] = list(top_guests.values_list('username', flat=True))  # top_guest_names
        return context

    def get_success_url(self):
        messages.success(self.request, 'Your event has been created!')
        return reverse('event-list-host', args=(self.request.user.id,))

    def get_form_kwargs(self, **kwargs):
        kwargs = super(EventCreateView, self).get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs

    def form_valid(self, form):
        form.instance.host = self.request.user
        rsvp_date = form.instance.RSVP_date
        event_date = form.instance.event_date
        try:
            if not rsvp_date < event_date:
                raise forms.ValidationError(
                    'RSVP date must be prior to event date.'
                )
        except:
            if rsvp_date is None:
                raise forms.ValidationError(
                    'RSVP date is not a valid date.'
                )
            if event_date is None:
                raise forms.ValidationError(
                    'Event date is not a valid date.'
                )
        return super().form_valid(form)


class EventUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Event
    form_class = EventUpdateForm

    def get_success_url(self):
        messages.success(self.request, 'Your event has been updated!')
        return reverse('event-list-host', args=(self.request.user.id,))

    def get_form_kwargs(self, **kwargs):
        kwargs = super(EventUpdateView, self).get_form_kwargs()
        event = self.get_object()
        # invited_users = event.guests.all().distinct()
        # uninvited_users = User.objects.exclude(id__in=[guest.id for guest in invited_users] + [self.request.user.id])
        kwargs.update({'request': self.request})  # , 'uninvited_users': uninvited_users})
        return kwargs

    def test_func(self):
        event = self.get_object()
        if self.request.user == event.host:
            return True
        return False


class EventDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Event

    def test_func(self):
        user = self.request.user
        event = Event.objects.get(id=self.kwargs['pk'])
        if user in event.guests.all() or user == event.host:
            return True
        return False

    def get_context_data(self, **kwargs):
        context = super(EventDetailView, self).get_context_data(**kwargs)
        user = self.request.user
        event = Event.objects.get(id=self.kwargs['pk'])
        if event.host == user:
            context['hosting'] = True
            unresponsive = Invitation.objects.filter(event=event, replied=False)
            attending = Invitation.objects.filter(event=event, replied=True, attending=True)
            context['invitations_unresponsive'] = unresponsive
            context['invitations_attending'] = attending
            context['invitations_not_attending'] = Invitation.objects.filter(event=event, replied=True, attending=False)
            potential_profiles = Profile.objects.filter(Q(user__in=unresponsive.values_list('guest').distinct())
                                                        | Q(user__in=attending.values_list('guest').distinct()))
            context['restrictions'] = RestrictionTag.objects.filter(id__in=potential_profiles.values_list('restrictions').distinct())
            # TODO:
            #  get the profile of each guest in attendance
            #  use this profile to get the dietary restrictions of each guest
            #  and then pass that list on to the context
            # possible_invitations = Invitation.objects.filter(Q(event=event), Q(replied=False) | Q(replied=True, attending=True))
        else:
            unresponsive = Invitation.objects.filter(event=event, replied=False)
            attending = Invitation.objects.filter(event=event, replied=True, attending=True)
            context['invitations_unresponsive'] = unresponsive
            context['invitations_attending'] = attending
            context['invitations_not_attending'] = Invitation.objects.filter(event=event, replied=True, attending=False)
            potential_profiles = Profile.objects.filter(Q(user__in=unresponsive.values_list('guest').distinct())
                                                        | Q(user__in=attending.values_list('guest').distinct()))
            context['restrictions'] = RestrictionTag.objects.filter(id__in=potential_profiles.values_list('restrictions').distinct())
            rsvp = Invitation.objects.get(event=event, guest=user)
            context['food'] = rsvp.food
            context['RSVP_id'] = rsvp.id
            context['RSVP_replied'] = rsvp.replied
        return context


class EventListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Event

    def test_func(self):
        viewer = self.request.user
        user = User.objects.get(id=self.kwargs['user_id'])
        if viewer == user:
            return True
        return False


class EventHostListView(EventListView):

    def get_queryset(self):
        host = self.kwargs['user_id']
        return Event.objects.filter(host=host)

    def get_context_data(self, **kwargs):
        context = super(EventHostListView, self).get_context_data(**kwargs)
        context['status'] = 'hosting'
        return context


class EventGuestListView(EventListView):

    def get_queryset(self):
        RSVP_status = self.kwargs['RSVP_status']
        guest = self.kwargs['user_id']

        RSVP_filter = {
            'new': Invitation.objects.filter(guest=guest, replied=False),
            'attending': Invitation.objects.filter(guest=guest, attending=True),
            'all': Invitation.objects.filter(guest=guest),
        }
        invitation = RSVP_filter[RSVP_status]
        return Event.objects.filter(invitation__in=invitation)

    def get_context_data(self, **kwargs):
        context = super(EventGuestListView, self).get_context_data(**kwargs)
        context['status'] = self.kwargs.get('RSVP_status')
        return context


class InvitationResponseView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Invitation
    form_class = InvitationResponseForm

    def get_success_url(self):
        instance = self.get_object()
        if not instance.attending:
            messages.success(self.request, 'You have declined this event. Check out your other events below!')
            return reverse('event-list-guest', args=('attending', self.request.user.id))
        else:
            messages.success(self.request, 'Your response has been saved. Please select a food item to provide.')
            return reverse('event-response-food', args=(instance.pk,))

    def get_context_data(self, **kwargs):
        context = super(InvitationResponseView, self).get_context_data(**kwargs)
        context['event'] = self.get_object().event
        return context

    def test_func(self):
        user = self.request.user
        invitation = self.get_object()
        if user == invitation.guest:
            return True
        return False


class InvitationFoodView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Invitation
    form_class = InvitationFoodForm

    def get_success_url(self):
        messages.success(self.request, 'Your RSVP is complete!')
        return reverse('event-list-guest', args=('attending', self.request.user.id))

    def get_context_data(self, **kwargs):
        context = super(InvitationFoodView, self).get_context_data(**kwargs)
        context['event'] = self.get_object().event
        menu = self.get_object().event.menu
        menu_foods = menu.foods.all()
        menu_proportions = Proportion.objects.filter(menu=menu)
        if menu_proportions:
            # TODO : FIX THE TAG SELECTORS AND MAKE SURE THIS FILTERS ONLY THOSE TAGS IN USE
            valid_tags = get_valid_tags(menu, menu_proportions)
            tags = list()
            for tag in valid_tags:
                tags.append(Tag.objects.get(id=tag))
            try:
                required_tags = get_required_tags(menu)
                theme = list()
                for tag in required_tags:
                    theme.append(Tag.objects.get(id=tag))
                context['theme'] = theme
            except:
                pass
            context['tags'] = tags
            context['tagged_event'] = True

events/templates/events/create.html
<!-- events/create.html -->

{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
    <div class="content">
        <h3>Consider inviting your top invitees:</h3>
        <div>
            {% for guest in top_guests %}
                {{ guest }}
            {% endfor %}
        </div>
    </div>
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Create a new event!</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Create Event</button>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'user-view' user.id %}">Cancel</a>
        </div>
    </form>
</div>
{% endblock %}

events/templates/events/list.html
<!-- events/list.html -->

{% extends "base.html" %}

{% block content %}
<div class="content-section">
    <h2 class='text-muted'>
        {% if status == 'attending' %}
            Events you are attending:
        {% elif status == 'new' %}
            New invitations:
        {% elif status == 'all' %}
            Events you have been invited to:
        {% elif status == 'hosting' %}
            Events you are hosting:
        {% endif %}
    </h2>
    {% if not event_list %}
    <p>
        Nothing to show right now. Why not <a href="{% url 'event-create' %}">create an event</a> yourself?
    </p>
    {% else %}
    <br>
        {% for event in event_list %}
            <div>
                <a href="{% url 'event-view' event.id %}">{{ event }}</a>
                    <font size=-1 class='text-muted'>on {{ event.event_date }}</font>
                <p class='text-muted'>
                    <font size='-1'>
                        {% if status != 'attending' and status != 'hosting' %}
                            RSVP by {{ event.RSVP_date }}.
                        {% endif %}
                    </font>
                </p>
            </div>
        {% endfor %}
    {% endif %}
</div>


{% endblock content %}

events/templates/events/update.html
<!-- events/update.html -->

{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Create a new event!</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Update Event</button>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'user-view' user.id %}">Cancel</a>
        </div>
    </form>
</div>
{% endblock %}

events/templates/events/view.html
<!-- events/view.html -->

{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <div>
            <h1>Welcome to {{ object.title }}!</h1>
        </div>
        <div class="content-section">
            {% if not hosting %}
            <h2>
                Who?
            </h2>
            <p class="muted">
                Hosted by {{ object.host.first_name }} {{ object.host.last_name }} (<a href="{% url 'user-view' object.host.id %}">{{ object.host.username }}</a>)
            </p>
            <h4>
                Attending:
            </h4>
            <p class="muted">
                {% for invitation in invitations_attending %}
                    <p>
                        {{ invitation.guest.first_name }} {{ invitation.guest.last_name }}  : {% if invitation.food %} bringing {{ invitation.food }} {% else %} bringing nothing {% endif %}
                    </p>
                {% endfor %}
            </p>
            <h4>
                Dietary Restrictions To Account For:
            </h4>
            <p class="muted">
                {% for restriction in restrictions %}
                    <p>
                        {{ restriction }}
                    </p>
                {% endfor %}
            </p>
            {% else %}
            <h2>
                Who?
            </h2>
            <h4>
                Attending:
            </h4>
            <p class="muted">
                {% for invitation in invitations_attending %}
                    <p>
                        {{ invitation.guest.first_name }} {{ invitation.guest.last_name }}  : {% if invitation.food %} bringing {{ invitation.food }} {% else %} bringing nothing {% endif %}
                    </p>
                {% endfor %}
            </p>
            <h4>
                Not Attending:
            </h4>
            <p class="muted">
                {% for invitation in invitations_not_attending %}
                    <p>
                        {{ invitation.guest.first_name }} {{ invitation.guest.last_name }} ({{ invitation.guest }})
                    </p>
                {% endfor %}
            </p>
            <h4>
                Not Responded:
            </h4>
            <p class="muted">
                {% for invitation in invitations_unresponsive %}
                    <p>
                        {{ invitation.guest.first_name }} {{ invitation.guest.last_name }} ({{ invitation.guest }})
                    </p>
                {% endfor %}
            </p>
            <h4>
                Dietary Restrictions:
            </h4>
            <p class="muted">
                {% for restriction in restrictions %}
                    <p>
                        {{ restriction }}
                    </p>
                {% endfor %}
            </p>
            <a href="{% url 'event-update' object.id %}">Edit guest list here!</a>
            {% endif %}
        </div>
        {% if not hosting and RSVP_replied %}
        <div class="content-section">
            <h2>
                What?
            </h2>
            {% if food %}
                <h4 class="muted">
                    You are signed up to bring:
                </h4>
                <p>
                    {{ food }}
                </p>
            {% else %}
                <h4 class="muted">
                    You are not signed up to bring anything.
                </h4>
                <p>
                    <a href="{% url 'event-response-food' RSVP_id %}">Sign up here.</a>
                </p>
            {% endif %}
        </div>
        {% endif %}
        <div class="content-section">
            <h2>
                Where?
            </h2>
            <p class="muted">
                {{ object.event_location }}
            </p>
        </div>
        <div class="content-section">
            <h2>
                When?
            </h2>
            <p class="muted">
                {{ object.event_date|date:"F d, Y" }} at {{ object.event_time|date:"P" }}
            </p>
        </div>
        {% if not hosting %}
        <div class="content-section">
            <h2>RSVP</h2>
            {% if not RSVP_replied %}
                <h4>
                    Please RSVP by {{ object.RSVP_date|date:"F d, Y" }}.
                </h4>
                <p>
                    <a href="{% url 'event-response' RSVP_id %}">RSVP here!</a>
                </p>
            {% else %}
                <p>
                    You have already replied to this event.
                </p>
            {% endif %}
        </div>
        {% endif %}
    </div>
{% endblock content %}